### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by sachincool** [Decoys-out/Gallery#1]
# Todo :-
- [x] add Hover menu on side of Main page 
- [x] add  particle js on loader page
- [ ] add Side slide  on welcoming screen
- [ ] add autoscrolling  feature on main page
- [ ] add some  images which scrollspy  when  the particular item is  clicked on  menu 
- [ ] add some cool animations and  a last  item named " Fun stuff Skadoosh" 
- [ ] add `monkey vala effect`
